version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "wordCounter:1:1"
      KAFKA_ADVERTISED_PORT: "9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  spark:
    image: godatadriven/pyspark:2.4.3
    container_name: PySparkConsumer
    links:
      - kafka  
